[package]
name = "memo-cache"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rand = "0.8.5"

[features]
default = ["inline-more"]

# Enable more inlining of functions at the cost of compile time (enabled by default).
inline-more = []
